spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamemonitoring
    username: admin
    password: admin
  data:
    jdbc:
      dialect: postgresql

jwt:
  secret: 5856dde068735f8d962a56a0743a94e8858ea330ef03161abad043df3c8c8427
  expiration: 28800000